### ISSUE TITLE
Online BibTex Tidy seems non-functional - javascript errors?

### ISSUE THREAD

**Issue by LS31** [FlamingTempura/bibtex-tidy#10] opened 2020-04-05 09:06 UTC
I remember an earlier version of the bibtex-tidy online website and I really liked it to clean up messy bibtex files. However, the current version seems not to work: clicking 'Tidy' at https://flamingtempura.github.io/bibtex-tidy/ doesn't do anything. 

Firefox Developer Console gives the following two Javascript errors (on page load; with no new errors when clicking the 'Tidy' button).
```
SyntaxError: invalid regular expression flag s                     bibtex-tidy.js:2207:46
ReferenceError: bibtexTidy is not defined                          main.js:53:12
    <anonymous> https://flamingtempura.github.io/bibtex-tidy/main.js:53
```

(Latest Firefox 74.0.1. The problem occurs also with all add-ons disabed).

**Comment by FlamingTempura** [comment] 2020-04-05 11:01
Thanks for letting me know, I can confirm it's not working in firefox because of a change last week. I'll fix asap.

In the mean time, it's working in Chrome

**Comment by FlamingTempura** [comment] 2020-04-05 14:21
Should be fixed now!

It was caused by ES2018's new dotall regexp flag not yet being supported in Firefox.

**Closed by FlamingTempura** 2020-04-05 14:21 UTC

**Comment by LS31** [comment] 2020-04-06 16:39
Thanks for the very quick fix
